### ISSUE TITLE
Multiple calls to getDistance() and getAngularDisplacement() in the same expression

### ISSUE THREAD

**Issue by platisd** [Georgesarkis/DIT112#1]
In multiple occasions, pretty much all the Arduino sketches at the moment, you are using multiple calls to `getDistance` of IR or ultrasonic sensors as well as `getAngularDisplacement` of the gyroscope, in the same expression. Each time you make such a call you are getting a **new** measurement, meaning that aside of slowing down your code, the value could have changed!

This can introduce nasty and hard to find bugs that will reduce the reliability of your product. Please fix this asap.

**Comment by TiEkl** [comment]
Sorry for a late response.
It should be fixed now! We put them in variables and use that instead of the method calls.
